/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrera;

import com.imagen.ClaseImagen;
import javax.swing.JFrame;

public class PrincipalCarrera extends javax.swing.JFrame {

    int ancho = 1000;
    ClaseImagen img = new ClaseImagen();
    Thread sound = new Thread(new Sonido());

    public PrincipalCarrera() {
        initComponents();
        lbMeta.setText("<HTML>M<br>E<br>T<br>A</HTML");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        btnEmpieza.setEnabled(true);
        sound.start();
        img.AjustarImagenL(lbLobo, "imagenes", "Lobo", "gif");
        img.AjustarImagenL(lbCaballo, "imagenes", "Caballo", "gif");
        img.AjustarImagenL(lbZorro, "imagenes", "Zorro", "gif");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbMeta = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lbCaballo = new javax.swing.JLabel();
        lbZorro = new javax.swing.JLabel();
        lbLobo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnEmpieza = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1830, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 1830, 10));

        lbMeta.setFont(new java.awt.Font("NSimSun", 1, 48)); // NOI18N
        lbMeta.setText("Meta");
        jPanel1.add(lbMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 220, 30, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 0, 20, 840));
        jPanel1.add(lbCaballo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, 170));
        jPanel1.add(lbZorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 170, 170));
        jPanel1.add(lbLobo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 170, 170));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 740, -1, 80));

        btnEmpieza.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        btnEmpieza.setText("Empiece la carrera");
        btnEmpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpiezaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 750, 340, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tabla de posiciones");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 720, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpiezaActionPerformed

        Animal Lobo = new Animal("Lobo", jPanel1.getWidth() - 200, lbLobo, 20, txtArea);
        Animal Caballo = new Animal("Caballo", jPanel1.getWidth() - 200, lbCaballo, 250, txtArea);
        Animal Zorro = new Animal("Zorro", jPanel1.getWidth() - 200, lbZorro, 460, txtArea);
        Lobo.start();
        Caballo.start();
        Zorro.start();
        btnEmpieza.setEnabled(false);
    }//GEN-LAST:event_btnEmpiezaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalCarrera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpieza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbCaballo;
    private javax.swing.JLabel lbLobo;
    private javax.swing.JLabel lbMeta;
    private javax.swing.JLabel lbZorro;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
